apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rc-py
  labels:
    type: py
spec:
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: py
    spec:
      containers:
      - name: py-pod
        image: bbenetskyy/k8s-python-api:v1.0
        ports:
        - containerPort: 80