apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: version-api
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: version-api
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v0.5
        ports:
        - containerPort: 80
        #resources:
        #  requests:
        #    memory: "1024M"
        #    cpu: "5"
        #  limits:
        #    memory: "2048M"
        #    cpu: "10"
---
apiVersion: v1
kind: Service
metadata:
  name: version-api-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30500
  selector:
    app: version-api
  type: NodePort