apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: version-api
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: version-api
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v0.5
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64M"
            cpu: "250m"
          limits:
            memory: "128M"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: version-api-service
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 80
  selector:
    app: version-api
  type: LoadBalancer