apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: version-api
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: version-api
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v1.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64M"
            cpu: "250m"
          limits:
            memory: "128M"
            cpu: "500m"