apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: version-api-deploy
spec:
  replicas: 5
  template:
    metadata:
      labels:
        type: version-api
        app: v0.5
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v0.5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: version-api-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30500
  selector:
    type: version-api
  type: NodePort