apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: version-api-deploy
  labels:
    type: version-api
    app: v0.5
spec:
  replicas: 5
  template:
    metadata:
      labels:
        type: version-api
        app: v0.5
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v0.5
        ports:
        - containerPort: 80