apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: version-api-deploy-v2
spec:
  replicas: 5
  template:
    metadata:
      labels:
        type: version-api
        app: v2.0
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v2.0
        ports:
        - containerPort: 80