apiVersion: v1
kind: Service
metadata:
  name: version-api-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30500
  selector:
    type: version-api
  type: NodePort