FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /
EXPOSE 59518
EXPOSE 44364

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /
RUN dotnet restore Checker.csproj

FROM build AS publish
RUN dotnet publish Checker.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "HelloDockerTools.dll"]