apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-v0.5
  labels:
    app: v0.5
spec:
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: v0.5
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v0.5
        ports:
        - containerPort: 80