apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: py-v0.6
  labels:
    app: py-v0.6
spec:
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: py-v0.6
    spec:
      containers:
      - name: py-pod
        image: bbenetskyy/k8s-python-api:v0.6
        ports:
        - containerPort: 80