apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: py-v1.0
  labels:
    app: py-v1.0
spec:
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: py-v1.0
    spec:
      containers:
      - name: py-pod
        image: bbenetskyy/k8s-python-api:v1.0
        ports:
        - containerPort: 80