apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  #loadBalancerIP: 13.94.171.227
  #type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30500
  selector:
    app: v0.5
  type: NodePort