apiVersion: v1
kind: Service
metadata:
  name: py-svc
spec:
  #loadBalancerIP: 13.94.171.227
  #type: LoadBalancer
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30501
  selector:
    app: py-v0.6