apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: py-v1.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: py
    spec:
      containers:
      - name: py-pod
        image: bbenetskyy/k8s-python-api:v1.0
        ports:
        - containerPort: 80