apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: py-v0.5
spec:
  replicas: 5
  template:
    metadata:
      labels:
        type: py
    spec:
      containers:
      - name: py-pod
        image: bbenetskyy/k8s-python-api:v0.5
        ports:
        - containerPort: 80