apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-v1.1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: version-api
    spec:
      containers:
      - name: version-api-pod
        image: bbenetskyy/version-api:v1.1
        ports:
        - containerPort: 80